package Interfaces;

import Clases.Casa;
import Clases.Departamento;
import Clases.Propiedad;
import Estructura.ArrayListPropiedad;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class BuscarPorDireccion extends javax.swing.JPanel {
    private ProgramaPrincipal Principal;
    private ArrayListPropiedad Propiedades;
    private int opc;

    public BuscarPorDireccion(ArrayListPropiedad Propiedades,ProgramaPrincipal Principal,int opc) {
        initComponents();
        this.Propiedades=Propiedades;
        this.Principal=Principal;
        this.opc=opc;
    }
    public ArrayListPropiedad getPropiedades() {
        return Propiedades;
    }

    public void setPropiedades(ArrayListPropiedad Propiedades) {
        this.Propiedades = Propiedades;
    }
     public ProgramaPrincipal getPrincipal() {
        return Principal;
    }

    public void setPrincipal(ProgramaPrincipal Principal) {
        this.Principal=Principal;
    }

    public int getOpc() {
        return opc;
    }

    public void setOpc(int opc) {
        this.opc = opc;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarDire = new javax.swing.JPanel();
        Arriba3 = new javax.swing.JPanel();
        Regresar2 = new javax.swing.JButton();
        LogoFacu = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Salir3 = new javax.swing.JButton();
        Ins = new javax.swing.JLabel();
        Diret = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();

        BuscarDire.setBackground(new java.awt.Color(255, 204, 204));

        Arriba3.setBackground(new java.awt.Color(153, 0, 51));

        Regresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        Regresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar2ActionPerformed(evt);
            }
        });

        LogoFacu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoFacultad.png"))); // NOI18N

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Busqueda por Direccion");

        javax.swing.GroupLayout Arriba3Layout = new javax.swing.GroupLayout(Arriba3);
        Arriba3.setLayout(Arriba3Layout);
        Arriba3Layout.setHorizontalGroup(
            Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Arriba3Layout.createSequentialGroup()
                .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Arriba3Layout.setVerticalGroup(
            Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Arriba3Layout.createSequentialGroup()
                .addGroup(Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Arriba3Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Title)))
                    .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        Salir3.setBackground(new java.awt.Color(255, 0, 0));
        Salir3.setText("Salir");
        Salir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir3ActionPerformed(evt);
            }
        });

        Ins.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Ins.setText("Ingresar Direccion.");

        Diret.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Aceptar.setBackground(new java.awt.Color(102, 102, 255));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarDireLayout = new javax.swing.GroupLayout(BuscarDire);
        BuscarDire.setLayout(BuscarDireLayout);
        BuscarDireLayout.setHorizontalGroup(
            BuscarDireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Arriba3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BuscarDireLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(18, 18, 18)
                .addComponent(Salir3)
                .addContainerGap())
            .addGroup(BuscarDireLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(BuscarDireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ins)
                    .addComponent(Diret, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarDireLayout.setVerticalGroup(
            BuscarDireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarDireLayout.createSequentialGroup()
                .addComponent(Arriba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Ins)
                .addGap(18, 18, 18)
                .addComponent(Diret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(BuscarDireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aceptar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BuscarDire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BuscarDire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar2ActionPerformed
        this.setVisible(false);
        try {
                    this.finalize();
                    } catch (Throwable ex) {}
        PanelAdmPropiedades panel=new PanelAdmPropiedades(Propiedades,this.Principal);
        this.Principal.setSize(767,808);
        this.Principal.setContentPane(panel);
    }//GEN-LAST:event_Regresar2ActionPerformed

    private void Salir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir3ActionPerformed
        Salir();
    }//GEN-LAST:event_Salir3ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        String p="";
        p=Diret.getText();
        if(p.isEmpty()){
            Ventana_Mensaje("No se ha ingresado ningun caracter","/imagenes/X.png","No se ingreso Ninguna Direccion");
        }
        else{
            Propiedad y2=Propiedades.buscarPropiedadPorDireccion(p);
            if(y2!=null){
                if (opc==0){
                MostrarUnico m1=new MostrarUnico(Propiedades,this.Principal,y2);
                 this.setVisible(false);
                try {
                    this.finalize();
                    } catch (Throwable ex) {}
                this.Principal.setSize(730,240);
                this.Principal.setContentPane(m1);
                }
                if(opc==1){
                    ConfirmaEli m1=new ConfirmaEli(Propiedades,this.Principal,y2);
                 this.setVisible(false);
                try {
                    this.finalize();
                    } catch (Throwable ex) {}
                this.Principal.setSize(810,240);
                this.Principal.setContentPane(m1);
                }
                 if(opc==2){
                     if (y2.getClass()==Casa.class){
                         ModificarProp m1=new ModificarProp(Propiedades,this.Principal, (Casa) y2);
                          this.setVisible(false);
                          try {
                                this.finalize();
                          } catch (Throwable ex) {}
                          this.Principal.setSize(505,610);
                          this.Principal.setContentPane(m1);
                     }
                     if (y2.getClass()==Departamento.class){
                         ModificarProp2 m1=new ModificarProp2(Propiedades,this.Principal, (Departamento)y2);
                         this.setVisible(false);
                          try {
                                this.finalize();
                          } catch (Throwable ex) {}
                          this.Principal.setSize(495,610);
                          this.Principal.setContentPane(m1);
                     }
                }
               
            }
            else{
                Ventana_Mensaje("No se ha encontrado una Propiedad con la direccion ingresada","/imagenes/X.png","Direccion no cargada en el sistema");
            }
        }
    }//GEN-LAST:event_AceptarActionPerformed
public void Salir(){
     try{
         Propiedades.GuardarEnArchivoTxt();}
     catch(IOException e){
         JOptionPane.showMessageDialog(null,"Error guardando los archivos \n"+e.toString(),"Error",JOptionPane.ERROR_MESSAGE);}
        System.exit(1);
}

public void Ventana_Mensaje(String Imprimir, String imagen,String Titulo) {
    Icon icono = new javax.swing.ImageIcon(getClass().getResource(imagen));
    JLabel texto = new javax.swing.JLabel();
    texto.setFont(new java.awt.Font("Microsoft YaHei", 1, 16));
    texto.setText(Imprimir);
    JOptionPane.showMessageDialog(this, texto,Titulo, JOptionPane.PLAIN_MESSAGE, icono); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JPanel Arriba3;
    private javax.swing.JPanel BuscarDire;
    private javax.swing.JTextField Diret;
    private javax.swing.JLabel Ins;
    private javax.swing.JLabel LogoFacu;
    private javax.swing.JButton Regresar2;
    private javax.swing.JButton Salir3;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
