package Interfaces;

import Clases.Casa;
import Clases.Hipoteca;
import Clases.Persona;
import Estructura.ArrayListPropiedad;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class ModificarProp extends javax.swing.JPanel {
     private ProgramaPrincipal Principal;
    private ArrayListPropiedad Propiedades;
    private Casa aux;
    
     double x=10000000 + Math.random() * 90000000;
    int x1=(int)x;
    double x2=10000 + Math.random() * 90000;
    int x3=(int)x2;
    
    Hipoteca h=new Hipoteca(25000,10,"13/03/2002","13/03/2030",123456,Integer.toString(x3));
     Persona Per=new Persona(x1,"Juan","Rodriguez",266420513,"juanmatupa@gmail.com",2044076065,3000);
    int aux2;
    
    public ModificarProp(ArrayListPropiedad Propiedades,ProgramaPrincipal Principal,Casa aux) {
        initComponents();
        this.Propiedades=Propiedades;
        this.Principal=Principal;
        this.aux=aux;
        this.Antigu.setText(""+aux.getAntiguedadDeConstruccion());
        this.Diret.setText(aux.getDireccion());
        this.CantAmbT.setText(""+aux.getCantidadDeAmbientes());
        this.M2Ct.setText(""+aux.getMetrosCuadradosCubiertos());
        this.M2tt.setText(""+aux.getMetrosCuadradosTotales());
        this.Vtt.setText(""+aux.getValorDeTasacion());
        
    }
     public ArrayListPropiedad getPropiedades() {
        return Propiedades;
    }

    public void setPropiedades(ArrayListPropiedad Propiedades) {
        this.Propiedades = Propiedades;
    }
     public ProgramaPrincipal getPrincipal() {
        return Principal;
    }

    public void setPrincipal(ProgramaPrincipal Principal) {
        this.Principal=Principal;
    }

    public Casa getAux() {
        return aux;
    }

    public void setAux(Casa aux) {
        this.aux = aux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModiProp = new javax.swing.JPanel();
        Arriba3 = new javax.swing.JPanel();
        Titulo3 = new javax.swing.JLabel();
        Regresar2 = new javax.swing.JButton();
        LogoFacu = new javax.swing.JLabel();
        Salir3 = new javax.swing.JButton();
        Diret = new javax.swing.JTextField();
        Vtt = new javax.swing.JTextField();
        M2tt = new javax.swing.JTextField();
        CantAmbT = new javax.swing.JTextField();
        dir = new javax.swing.JLabel();
        tasacion = new javax.swing.JLabel();
        ambientes = new javax.swing.JLabel();
        m2cub = new javax.swing.JLabel();
        m2tot = new javax.swing.JLabel();
        M2Ct = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        Antigu = new javax.swing.JTextField();
        Anti = new javax.swing.JLabel();

        ModiProp.setBackground(new java.awt.Color(255, 204, 204));

        Arriba3.setBackground(new java.awt.Color(153, 0, 51));

        Titulo3.setBackground(new java.awt.Color(255, 255, 255));
        Titulo3.setFont(new java.awt.Font("Arial", 3, 30)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(255, 255, 255));
        Titulo3.setText("Modificar Propiedad");
        Titulo3.setToolTipText("");

        Regresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        Regresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar2ActionPerformed(evt);
            }
        });

        LogoFacu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoFacultad.png"))); // NOI18N

        javax.swing.GroupLayout Arriba3Layout = new javax.swing.GroupLayout(Arriba3);
        Arriba3.setLayout(Arriba3Layout);
        Arriba3Layout.setHorizontalGroup(
            Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Arriba3Layout.createSequentialGroup()
                .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Arriba3Layout.setVerticalGroup(
            Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Arriba3Layout.createSequentialGroup()
                .addGroup(Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Arriba3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Salir3.setBackground(new java.awt.Color(255, 0, 0));
        Salir3.setText("Salir");
        Salir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir3ActionPerformed(evt);
            }
        });

        dir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dir.setText("Direccion");

        tasacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tasacion.setText("Valor de Tasacion");

        ambientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ambientes.setText("Cantidad De Ambientes");

        m2cub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m2cub.setText("Metros Cuadrados Cubiertos");

        m2tot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m2tot.setText("Metros Cuadrados Totales");

        Modificar.setBackground(new java.awt.Color(51, 255, 51));
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Anti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Anti.setText("Antiguedad (En años)");

        javax.swing.GroupLayout ModiPropLayout = new javax.swing.GroupLayout(ModiProp);
        ModiProp.setLayout(ModiPropLayout);
        ModiPropLayout.setHorizontalGroup(
            ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Arriba3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModiPropLayout.createSequentialGroup()
                .addGroup(ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ModiPropLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModiPropLayout.createSequentialGroup()
                                .addGroup(ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(m2cub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tasacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(m2tot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Diret, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ambientes)
                                    .addComponent(M2Ct, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(M2tt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantAmbT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Vtt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(Antigu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(ModiPropLayout.createSequentialGroup()
                                .addComponent(dir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Anti)
                                .addGap(11, 11, 11))))
                    .addGroup(ModiPropLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Modificar)
                        .addGap(36, 36, 36)
                        .addComponent(Salir3)))
                .addGap(30, 30, 30))
        );
        ModiPropLayout.setVerticalGroup(
            ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModiPropLayout.createSequentialGroup()
                .addComponent(Arriba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dir)
                    .addComponent(Anti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Antigu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(tasacion)
                .addGap(14, 14, 14)
                .addComponent(Vtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(ambientes)
                .addGap(12, 12, 12)
                .addComponent(CantAmbT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(m2cub)
                .addGap(20, 20, 20)
                .addComponent(M2Ct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(m2tot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(M2tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ModiPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ModiProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ModiProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar2ActionPerformed
        PanelAdmPropiedades a12=new PanelAdmPropiedades(Propiedades,this.Principal);
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {}
        this.Principal.setSize(767,808);
        this.Principal.setContentPane(a12);
    }//GEN-LAST:event_Regresar2ActionPerformed

    private void Salir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir3ActionPerformed
        Salir();
    }//GEN-LAST:event_Salir3ActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String direccion,id; double vt,m2c,m2t; int ct,ant,piso;
        id=aux.getDireccion();
        if (Diret.getText().isEmpty() || CantAmbT.getText().isEmpty() || Vtt.getText().isEmpty() || M2tt.getText().isEmpty() || M2Ct.getText().isEmpty() || Antigu.getText().isEmpty()){
            Ventana_Mensaje("Hay campos sin completar!","Hay campos vacios");
            return;
        }
         try{
             direccion=Diret.getText();
              vt=Double.parseDouble(Vtt.getText());
              ct=Integer.parseInt(CantAmbT.getText());
              m2c=Double.parseDouble(M2Ct.getText());
              m2t=Double.parseDouble(M2tt.getText());
              ant=Integer.parseInt(Antigu.getText());
            }catch(NumberFormatException e){
                Ventana_Mensaje("Hay campos invalidos!!","Error, Campos Invalidos");
                return;}
          if (m2c > m2t){
              Ventana_Mensaje("Los metros Cubiertos no pueden ser mayores a los totales","Metros Cubiertos > Totales");
             return;
         }
                aux2=Propiedades.indexOfPropiedad(aux);
                Propiedades.remove(aux);
                Casa c1=new Casa(ant,Per,h,direccion,vt,ct,m2c,m2t);
                Propiedades.add(aux2,c1);
                Ventana_Mensaje("Se ha modificado la propiedad exitosamente!","Propiedad modificada Correctamente");
                PanelAdmPropiedades a12=new PanelAdmPropiedades(Propiedades,this.Principal);
                this.setVisible(false);
                try {
                    this.finalize();
                } catch (Throwable ex) {}
                this.Principal.setSize(767,808);
                this.Principal.setContentPane(a12);
    }//GEN-LAST:event_ModificarActionPerformed
public void Salir(){
     try{
         Propiedades.GuardarEnArchivoTxt();}
     catch(IOException e){
         JOptionPane.showMessageDialog(null,"Error guardando los archivos \n"+e.toString(),"Error",JOptionPane.ERROR_MESSAGE);}
        System.exit(1);
}
  
public void Ventana_Mensaje(String Imprimir,String  Titulo){
    JLabel texto = new javax.swing.JLabel();
    texto.setFont(new java.awt.Font("Microsoft YaHei", 1, 16));
    texto.setText(Imprimir);
    JOptionPane.showMessageDialog(this, texto,Titulo, JOptionPane.PLAIN_MESSAGE); 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anti;
    private javax.swing.JTextField Antigu;
    private javax.swing.JPanel Arriba3;
    private javax.swing.JTextField CantAmbT;
    private javax.swing.JTextField Diret;
    private javax.swing.JLabel LogoFacu;
    private javax.swing.JTextField M2Ct;
    private javax.swing.JTextField M2tt;
    private javax.swing.JPanel ModiProp;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Regresar2;
    private javax.swing.JButton Salir3;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JTextField Vtt;
    private javax.swing.JLabel ambientes;
    private javax.swing.JLabel dir;
    private javax.swing.JLabel m2cub;
    private javax.swing.JLabel m2tot;
    private javax.swing.JLabel tasacion;
    // End of variables declaration//GEN-END:variables
}
