package Interfaces;
import Clases.Hipoteca;
import Estructura.ArrayListPropiedad;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MostrarUnicoHipoteca extends javax.swing.JPanel {
    private ProgramaPrincipal Principal;
    private ArrayListPropiedad Propiedades;
    private Hipoteca h;
    
    public MostrarUnicoHipoteca(ArrayListPropiedad Propiedades,ProgramaPrincipal Principal,Hipoteca h) {
        initComponents();
        this.Propiedades=Propiedades;
        this.Principal=Principal;
        this.h=h;
        LlenadoTabla();
    }
     public ArrayListPropiedad getPropiedades() {
        return Propiedades;
    }

    public void setPropiedades(ArrayListPropiedad Propiedades) {
        this.Propiedades = Propiedades;
    }
     public ProgramaPrincipal getPrincipal() {
        return Principal;
    }

    public void setPrincipal(ProgramaPrincipal Principal) {
        this.Principal=Principal;
    }

    public Hipoteca getH() {
        return h;
    }

    public void setH(Hipoteca h) {
        this.h = h;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MostrarPanel = new javax.swing.JPanel();
        Arriba3 = new javax.swing.JPanel();
        Regresar2 = new javax.swing.JButton();
        LogoFacu = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Salir3 = new javax.swing.JButton();
        ScrollAux = new javax.swing.JScrollPane();
        Mostrar1 = new javax.swing.JTable();

        MostrarPanel.setBackground(new java.awt.Color(255, 204, 204));

        Arriba3.setBackground(new java.awt.Color(153, 0, 51));

        Regresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        Regresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar2ActionPerformed(evt);
            }
        });

        LogoFacu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoFacultad.png"))); // NOI18N

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Hipoteca Buscada");

        javax.swing.GroupLayout Arriba3Layout = new javax.swing.GroupLayout(Arriba3);
        Arriba3.setLayout(Arriba3Layout);
        Arriba3Layout.setHorizontalGroup(
            Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Arriba3Layout.createSequentialGroup()
                .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Arriba3Layout.setVerticalGroup(
            Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Arriba3Layout.createSequentialGroup()
                .addGroup(Arriba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Arriba3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Salir3.setBackground(new java.awt.Color(255, 0, 0));
        Salir3.setText("Salir");
        Salir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir3ActionPerformed(evt);
            }
        });

        Mostrar1 = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        Mostrar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Mostrar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Capital", "Interes Mensual", "Fecha Inicio", "Fecha Inicio", "Fecha Final", "Importe Cuota Mensual"
            }
        ));
        Mostrar1.setFocusable(false);
        Mostrar1.getTableHeader().setReorderingAllowed(false);
        ScrollAux.setViewportView(Mostrar1);

        javax.swing.GroupLayout MostrarPanelLayout = new javax.swing.GroupLayout(MostrarPanel);
        MostrarPanel.setLayout(MostrarPanelLayout);
        MostrarPanelLayout.setHorizontalGroup(
            MostrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Arriba3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MostrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MostrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostrarPanelLayout.createSequentialGroup()
                        .addGap(0, 947, Short.MAX_VALUE)
                        .addComponent(Salir3))
                    .addComponent(ScrollAux))
                .addContainerGap())
        );
        MostrarPanelLayout.setVerticalGroup(
            MostrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarPanelLayout.createSequentialGroup()
                .addComponent(Arriba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScrollAux, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MostrarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MostrarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar2ActionPerformed
        PanelAdmHipoteca i=new PanelAdmHipoteca(Propiedades,this.Principal);
        this.setVisible(false);
        try {
                    this.finalize();
                    } catch (Throwable ex) {}
        this.Principal.setSize(570,834);
        this.Principal.setContentPane(i);
    }//GEN-LAST:event_Regresar2ActionPerformed

    private void Salir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir3ActionPerformed
        Salir();
    }//GEN-LAST:event_Salir3ActionPerformed
public void Salir(){
     try{
         Propiedades.GuardarEnArchivoTxt();}
     catch(IOException e){
         JOptionPane.showMessageDialog(null,"Error guardando los archivos \n"+e.toString(),"Error",JOptionPane.ERROR_MESSAGE);}
        System.exit(1);
}
public void LlenadoTabla(){
 DefaultTableModel modelo= new javax.swing.table.DefaultTableModel(
            new Object [][] {
            
            },
            new String [] {
                "ID","Capital", "Interes Mensual", "Fecha Inicio","Fecha Final","Importe Cuota Mensual"
            }
        );
            modelo.addRow(new String[] {""+h.getID(),""+h.getCapital(),""+h.getInteresMensual(),""+h.getFechaInicio(),""+h.getFechaFinal(),""+h.getImporteCuotaMensual()});
        this.Mostrar1.setModel(modelo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arriba3;
    private javax.swing.JLabel LogoFacu;
    private javax.swing.JTable Mostrar1;
    private javax.swing.JPanel MostrarPanel;
    private javax.swing.JButton Regresar2;
    private javax.swing.JButton Salir3;
    private javax.swing.JScrollPane ScrollAux;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

}
