package Interfaces;

import Clases.Hipoteca;
import Clases.Propiedad;
import Estructura.ArrayListPropiedad;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class PanelAdmHipoteca extends javax.swing.JPanel {
    private ProgramaPrincipal Principal;
     private ArrayListPropiedad Propiedades;

    public PanelAdmHipoteca(ArrayListPropiedad Propiedades,ProgramaPrincipal Principal) {
        initComponents();
        this.Propiedades=Propiedades;
        this.Principal=Principal;
    }
    public ArrayListPropiedad getPropiedades() {
        return Propiedades;
    }

    public void setPropiedades(ArrayListPropiedad Propiedades) {
        this.Propiedades = Propiedades;
    }
     public ProgramaPrincipal getPrincipal() {
        return Principal;
    }

    public void setPrincipal(ProgramaPrincipal Principal) {
        this.Principal=Principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdmHipotecas = new javax.swing.JPanel();
        Arriba = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        LogoFacu = new javax.swing.JLabel();
        CargarHipotecaIm = new javax.swing.JLabel();
        Baja0 = new javax.swing.JLabel();
        Modi0 = new javax.swing.JLabel();
        Salir2 = new javax.swing.JButton();
        EliminarHipoteca = new javax.swing.JButton();
        ModificarHipoteca = new javax.swing.JButton();
        CargarHipoteca = new javax.swing.JButton();
        MostrarHipotecas = new javax.swing.JButton();
        Buscar0 = new javax.swing.JButton();
        Buscar1 = new javax.swing.JButton();
        Mostrar0 = new javax.swing.JButton();
        Mostrar1 = new javax.swing.JLabel();
        MostrarIm = new javax.swing.JLabel();
        Mostrar2 = new javax.swing.JButton();

        PanelAdmHipotecas.setBackground(new java.awt.Color(255, 204, 204));
        PanelAdmHipotecas.setPreferredSize(new java.awt.Dimension(564, 794));

        Arriba.setBackground(new java.awt.Color(153, 0, 51));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Arial", 3, 42)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Administrar Hipotecas");
        Titulo.setToolTipText("");

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        LogoFacu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoFacultad.png"))); // NOI18N

        javax.swing.GroupLayout ArribaLayout = new javax.swing.GroupLayout(Arriba);
        Arriba.setLayout(ArribaLayout);
        ArribaLayout.setHorizontalGroup(
            ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArribaLayout.createSequentialGroup()
                .addGroup(ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArribaLayout.createSequentialGroup()
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 363, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArribaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ArribaLayout.setVerticalGroup(
            ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArribaLayout.createSequentialGroup()
                .addGroup(ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArribaLayout.createSequentialGroup()
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CargarHipotecaIm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CargarHipoteca.png"))); // NOI18N

        Baja0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N

        Modi0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N

        Salir2.setBackground(new java.awt.Color(255, 0, 0));
        Salir2.setText("Salir");
        Salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir2ActionPerformed(evt);
            }
        });

        EliminarHipoteca.setBackground(new java.awt.Color(255, 0, 51));
        EliminarHipoteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/X.png"))); // NOI18N
        EliminarHipoteca.setText("Eliminar Hipoteca");
        EliminarHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarHipotecaActionPerformed(evt);
            }
        });

        ModificarHipoteca.setBackground(new java.awt.Color(255, 255, 102));
        ModificarHipoteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        ModificarHipoteca.setText("Modificar Hipoteca");
        ModificarHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarHipotecaActionPerformed(evt);
            }
        });

        CargarHipoteca.setBackground(new java.awt.Color(102, 255, 102));
        CargarHipoteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Check.png"))); // NOI18N
        CargarHipoteca.setText("Cargar Hipoteca");
        CargarHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarHipotecaActionPerformed(evt);
            }
        });

        MostrarHipotecas.setBackground(new java.awt.Color(204, 255, 255));
        MostrarHipotecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        MostrarHipotecas.setText("Mostrar Hipotecas Cargadas");
        MostrarHipotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarHipotecasActionPerformed(evt);
            }
        });

        Buscar0.setBackground(new java.awt.Color(204, 204, 255));
        Buscar0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        Buscar0.setText("Buscar Hipoteca por ID");
        Buscar0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar0ActionPerformed(evt);
            }
        });

        Buscar1.setBackground(new java.awt.Color(204, 204, 255));
        Buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        Buscar1.setText("Buscar Hipoteca por Propietario");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });

        Mostrar0.setBackground(new java.awt.Color(204, 255, 255));
        Mostrar0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MayorMenor.png"))); // NOI18N
        Mostrar0.setText("Mostrar Hipoteca de mayor monto");
        Mostrar0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar0ActionPerformed(evt);
            }
        });

        Mostrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pregunta.png"))); // NOI18N

        MostrarIm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MostrarB.png"))); // NOI18N

        Mostrar2.setBackground(new java.awt.Color(204, 255, 255));
        Mostrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MayorMenor.png"))); // NOI18N
        Mostrar2.setText("Mostrar Hipoteca de menor monto");
        Mostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdmHipotecasLayout = new javax.swing.GroupLayout(PanelAdmHipotecas);
        PanelAdmHipotecas.setLayout(PanelAdmHipotecasLayout);
        PanelAdmHipotecasLayout.setHorizontalGroup(
            PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Arriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mostrar1)
                            .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                                    .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CargarHipotecaIm)
                                        .addComponent(Baja0))
                                    .addGap(49, 49, 49)
                                    .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EliminarHipoteca)
                                        .addComponent(CargarHipoteca)))
                                .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                                    .addComponent(Modi0)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModificarHipoteca)))
                            .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                                    .addComponent(MostrarIm)
                                    .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                                            .addGap(91, 91, 91)
                                            .addComponent(Mostrar2))
                                        .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                                            .addGap(93, 93, 93)
                                            .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Mostrar0)
                                                .addComponent(MostrarHipotecas, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                                    .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Buscar0, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Buscar1))
                                    .addGap(24, 24, 24))))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelAdmHipotecasLayout.setVerticalGroup(
            PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                .addComponent(Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(CargarHipotecaIm))
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CargarHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Baja0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Modi0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(EliminarHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModificarHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdmHipotecasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar1)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar0)
                        .addGap(17, 17, 17))
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Mostrar1)))
                .addGroup(PanelAdmHipotecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(MostrarIm))
                    .addGroup(PanelAdmHipotecasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(MostrarHipotecas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(Mostrar0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mostrar2)))
                .addGap(13, 13, 13)
                .addComponent(Salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelAdmHipotecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdmHipotecas, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Inicio a=new Inicio(Propiedades,this.Principal);
        this.setVisible(false);
        try {
            this.finalize();
        }catch(Throwable ex){}
        this.Principal.setSize(890,575);
        this.Principal.setContentPane(a);
    }//GEN-LAST:event_RegresarActionPerformed

    private void Salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir2ActionPerformed
        Salir();
    }//GEN-LAST:event_Salir2ActionPerformed

    private void EliminarHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarHipotecaActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_EliminarHipotecaActionPerformed

    private void ModificarHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarHipotecaActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_ModificarHipotecaActionPerformed

    private void CargarHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarHipotecaActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_CargarHipotecaActionPerformed

    private void MostrarHipotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarHipotecasActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_MostrarHipotecasActionPerformed

    private void Buscar0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar0ActionPerformed
        if(Propiedades.isEmpty()){
            Ventana_Mensaje("No hay Hipotecas cargadas","/imagenes/Emoji1.png");
        }
        else{
            Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
        /*BuscarPorIDHipoteca i1=new BuscarPorIDHipoteca(Propiedades,this.Principal,this);
        this.setVisible(false);
        try {
            this.finalize();
        }catch (Throwable ex){}
        this.Principal.setSize(433,315);
        this.Principal.setContentPane(i1);*/}
    }//GEN-LAST:event_Buscar0ActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
        if(Propiedades.isEmpty()){
            Ventana_Mensaje("No hay Hipotecas cargadas","/imagenes/Emoji1.png");
        }
        else{
            Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
        /*BuscarPorDNI b=new BuscarPorDNI(Propiedades,this.Principal,this);
        this.setVisible(false);
        try {
                    this.finalize();
                    } catch (Throwable ex) {}
        this.Principal.setSize(455,320);
        this.Principal.setContentPane(b);*/}
    }//GEN-LAST:event_Buscar1ActionPerformed

    private void Mostrar0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar0ActionPerformed
        if(Propiedades.isEmpty()){
            Ventana_Mensaje("No hay Hipotecas cargadas","/imagenes/Emoji1.png");}
        else{
        Propiedad n=Hipoteca.PrestamoDeMayor(Propiedades);
        Hipoteca h7=n.getHipoteca();
        MostrarUnicoHipoteca m1=new MostrarUnicoHipoteca(Propiedades,this.Principal,h7);
        this.setVisible(false);
        try {
                    this.finalize();
                    } catch (Throwable ex) {}
        this.Principal.setSize(1030,240);
        this.Principal.setContentPane(m1);
        }
    }//GEN-LAST:event_Mostrar0ActionPerformed

    private void Mostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar2ActionPerformed
         if(Propiedades.isEmpty()){
            Ventana_Mensaje("No hay Hipotecas cargadas","/imagenes/Emoji1.png");}
        else{
        Propiedad n1=Hipoteca.PrestamoDeMenor(Propiedades);
        Hipoteca h8=n1.getHipoteca();
        MostrarUnicoHipoteca m1=new MostrarUnicoHipoteca(Propiedades,this.Principal,h8);
        this.setVisible(false);
             try {
                 this.finalize();
             } catch (Throwable ex) {}
        this.Principal.setSize(1030,240);
        this.Principal.setContentPane(m1);
        }
    }//GEN-LAST:event_Mostrar2ActionPerformed
 public void Salir(){
     try{
         Propiedades.GuardarEnArchivoTxt();}
     catch(IOException e){
         JOptionPane.showMessageDialog(null,"Error guardando los archivos \n"+e.toString(),"Error",JOptionPane.ERROR_MESSAGE);}
        System.exit(1);
}

public void Ventana_Mensaje(String Imprimir, String imagen) {
    Icon icono = new javax.swing.ImageIcon(getClass().getResource(imagen));
    JLabel texto = new javax.swing.JLabel();
    texto.setFont(new java.awt.Font("Microsoft YaHei", 1, 16));
    texto.setText(Imprimir);
    JOptionPane.showMessageDialog(this, texto, "Lo sentimos!", JOptionPane.PLAIN_MESSAGE,icono); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arriba;
    private javax.swing.JLabel Baja0;
    private javax.swing.JButton Buscar0;
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton CargarHipoteca;
    private javax.swing.JLabel CargarHipotecaIm;
    private javax.swing.JButton EliminarHipoteca;
    private javax.swing.JLabel LogoFacu;
    private javax.swing.JLabel Modi0;
    private javax.swing.JButton ModificarHipoteca;
    private javax.swing.JButton Mostrar0;
    private javax.swing.JLabel Mostrar1;
    private javax.swing.JButton Mostrar2;
    private javax.swing.JButton MostrarHipotecas;
    private javax.swing.JLabel MostrarIm;
    private javax.swing.JPanel PanelAdmHipotecas;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir2;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
