package Interfaces;

import Estructura.ArrayListPropiedad;
import java.io.IOException;
import javax.swing.JOptionPane;

public class PanelCreador extends javax.swing.JPanel {
    private ProgramaPrincipal Principal;
     private ArrayListPropiedad Propiedades;

    public PanelCreador(ArrayListPropiedad Propiedades,ProgramaPrincipal Principal) {
        initComponents();
        this.Principal=Principal;
        this.Propiedades=Propiedades;
    }
    public ArrayListPropiedad getPropiedades() {
        return Propiedades;
    }

    public void setPropiedades(ArrayListPropiedad Propiedades) {
        this.Propiedades = Propiedades;
    }
    
    public ProgramaPrincipal getPrincipal() {
        return Principal;
    }

    public void setPrincipal(ProgramaPrincipal Principal) {
        this.Principal=Principal;
    }
    
    public void Salir(){
     try{
         Propiedades.GuardarEnArchivoTxt();}
     catch(IOException e){
         JOptionPane.showMessageDialog(null,"Error guardando los archivos \n"+e.toString(),"Error",JOptionPane.ERROR_MESSAGE);}
        System.exit(1);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCreadores = new javax.swing.JPanel();
        FotoJuan = new javax.swing.JLabel();
        NombreJuan = new javax.swing.JLabel();
        MailJuan = new javax.swing.JLabel();
        Unsl = new javax.swing.JLabel();
        Carrera = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Arriba = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        LogoFacu = new javax.swing.JLabel();

        PanelCreadores.setBackground(new java.awt.Color(255, 204, 204));

        FotoJuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FotoJuan.png"))); // NOI18N

        NombreJuan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NombreJuan.setText("Juan Manuel Sanchez");

        MailJuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MailJuan.setText("juanma2002123@gmail.com");

        Unsl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Unsl.setText("U.N.S.L 2021");

        Carrera.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Carrera.setText("Ingeniería en Informatica");

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSalir1ActionPerformed(evt);
            }
        });

        Arriba.setBackground(new java.awt.Color(153, 0, 51));
        Arriba.setPreferredSize(new java.awt.Dimension(600, 156));

        Titulo.setFont(new java.awt.Font("Arial", 3, 30)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Creador de la interfaz");

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarRegresarActionPerformed(evt);
            }
        });

        LogoFacu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoFacultad.png"))); // NOI18N

        javax.swing.GroupLayout ArribaLayout = new javax.swing.GroupLayout(Arriba);
        Arriba.setLayout(ArribaLayout);
        ArribaLayout.setHorizontalGroup(
            ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArribaLayout.createSequentialGroup()
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        ArribaLayout.setVerticalGroup(
            ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArribaLayout.createSequentialGroup()
                .addGroup(ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelCreadoresLayout = new javax.swing.GroupLayout(PanelCreadores);
        PanelCreadores.setLayout(PanelCreadoresLayout);
        PanelCreadoresLayout.setHorizontalGroup(
            PanelCreadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Arriba, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
            .addGroup(PanelCreadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCreadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCreadoresLayout.createSequentialGroup()
                        .addComponent(Unsl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCreadoresLayout.createSequentialGroup()
                        .addGroup(PanelCreadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreJuan)
                            .addComponent(MailJuan))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelCreadoresLayout.createSequentialGroup()
                        .addGroup(PanelCreadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FotoJuan)
                            .addComponent(Carrera))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelCreadoresLayout.setVerticalGroup(
            PanelCreadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCreadoresLayout.createSequentialGroup()
                .addComponent(Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FotoJuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NombreJuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MailJuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Carrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCreadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCreadoresLayout.createSequentialGroup()
                        .addComponent(Unsl)
                        .addContainerGap())
                    .addComponent(Salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelCreadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCreadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SalirSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSalir1ActionPerformed
        Salir();
    }//GEN-LAST:event_SalirSalir1ActionPerformed

    private void RegresarRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarRegresarActionPerformed
        Inicio a=new Inicio(Propiedades,this.Principal);
        this.setVisible(false);
        try {
            this.finalize();
        }catch(Throwable ex){}
        this.Principal.setSize(890,575);
        this.Principal.setContentPane(a);
    }//GEN-LAST:event_RegresarRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arriba;
    private javax.swing.JLabel Carrera;
    private javax.swing.JLabel FotoJuan;
    private javax.swing.JLabel LogoFacu;
    private javax.swing.JLabel MailJuan;
    private javax.swing.JLabel NombreJuan;
    private javax.swing.JPanel PanelCreadores;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Unsl;
    // End of variables declaration//GEN-END:variables
}
