package Interfaces;

import Estructura.ArrayListPropiedad;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class PanelAdmPersonas extends javax.swing.JPanel {
     private ProgramaPrincipal Principal;
     private ArrayListPropiedad Propiedades;

    public PanelAdmPersonas(ArrayListPropiedad Propiedades,ProgramaPrincipal Principal) {
        initComponents();
        this.Propiedades=Propiedades;
        this.Principal=Principal;
    }
    public ArrayListPropiedad getPropiedades() {
        return Propiedades;
    }

    public void setPropiedades(ArrayListPropiedad Propiedades) {
        this.Propiedades = Propiedades;
    }
     public ProgramaPrincipal getPrincipal() {
        return Principal;
    }

    public void setPrincipal(ProgramaPrincipal Principal) {
        this.Principal=Principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdmPersonas = new javax.swing.JPanel();
        Arriba = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        LogoFacu = new javax.swing.JLabel();
        CargarPersonaIm = new javax.swing.JLabel();
        Baja = new javax.swing.JLabel();
        Modi = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        EliminarPersona = new javax.swing.JButton();
        ModificarPersona = new javax.swing.JButton();
        CargarPersona = new javax.swing.JButton();
        MostrarPersonas = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Mostrar1 = new javax.swing.JLabel();
        Mostrar2 = new javax.swing.JButton();
        MostrarB = new javax.swing.JLabel();

        PanelAdmPersonas.setBackground(new java.awt.Color(255, 204, 204));

        Arriba.setBackground(new java.awt.Color(153, 0, 51));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Arial", 3, 42)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Administrar Personas");
        Titulo.setToolTipText("");

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        LogoFacu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoFacultad.png"))); // NOI18N

        javax.swing.GroupLayout ArribaLayout = new javax.swing.GroupLayout(Arriba);
        Arriba.setLayout(ArribaLayout);
        ArribaLayout.setHorizontalGroup(
            ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArribaLayout.createSequentialGroup()
                .addGroup(ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArribaLayout.createSequentialGroup()
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArribaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo)))
                .addGap(33, 33, 33)
                .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ArribaLayout.setVerticalGroup(
            ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArribaLayout.createSequentialGroup()
                .addGroup(ArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArribaLayout.createSequentialGroup()
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LogoFacu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CargarPersonaIm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarPersona.png"))); // NOI18N

        Baja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BorrarPersona.png"))); // NOI18N

        Modi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModificarPersona.png"))); // NOI18N

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        EliminarPersona.setBackground(new java.awt.Color(255, 0, 51));
        EliminarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/X.png"))); // NOI18N
        EliminarPersona.setText("Eliminar Persona");
        EliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPersonaActionPerformed(evt);
            }
        });

        ModificarPersona.setBackground(new java.awt.Color(255, 255, 102));
        ModificarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        ModificarPersona.setText("Modificar Persona");
        ModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPersonaActionPerformed(evt);
            }
        });

        CargarPersona.setBackground(new java.awt.Color(102, 255, 102));
        CargarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Check.png"))); // NOI18N
        CargarPersona.setText("Cargar Persona");
        CargarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarPersonaActionPerformed(evt);
            }
        });

        MostrarPersonas.setBackground(new java.awt.Color(204, 255, 255));
        MostrarPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        MostrarPersonas.setText("Mostrar Personas Cargadas");
        MostrarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPersonasActionPerformed(evt);
            }
        });

        Mostrar.setBackground(new java.awt.Color(204, 255, 255));
        Mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        Mostrar.setText("Mostrar 10 personas con prestamos vigentes mas cortos en cuotas");
        Mostrar.setActionCommand("Mostrar Listado de 10 personas con Prestamos vigentes mas cortos en cuotas");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        Buscar.setBackground(new java.awt.Color(204, 204, 255));
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        Buscar.setText("Buscar Persona por DNI");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Mostrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarPersona.png"))); // NOI18N

        Mostrar2.setBackground(new java.awt.Color(204, 255, 255));
        Mostrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        Mostrar2.setText("Mostrar 10 personas con prestamos no vigentes mas largos en cuotas");
        Mostrar2.setActionCommand("Mostrar Listado de 10 personas con Prestamos vigentes mas cortos en cuotas");
        Mostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar2ActionPerformed(evt);
            }
        });

        MostrarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MostrarB.png"))); // NOI18N

        javax.swing.GroupLayout PanelAdmPersonasLayout = new javax.swing.GroupLayout(PanelAdmPersonas);
        PanelAdmPersonas.setLayout(PanelAdmPersonasLayout);
        PanelAdmPersonasLayout.setHorizontalGroup(
            PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Arriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Mostrar1)
                            .addComponent(Baja)
                            .addComponent(CargarPersonaIm)
                            .addComponent(Modi))
                        .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModificarPersona)
                                    .addComponent(CargarPersona)
                                    .addComponent(EliminarPersona)
                                    .addComponent(Buscar)))
                            .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(MostrarPersonas))))
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(Salir))
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MostrarB)
                        .addGap(18, 18, 18)
                        .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mostrar)
                            .addComponent(Mostrar2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAdmPersonasLayout.setVerticalGroup(
            PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                .addComponent(Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(CargarPersonaIm))
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(CargarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Baja))
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(EliminarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Modi))
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(ModificarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(Mostrar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MostrarPersonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdmPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAdmPersonasLayout.createSequentialGroup()
                        .addComponent(Mostrar)
                        .addGap(18, 18, 18)
                        .addComponent(Mostrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MostrarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdmPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdmPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Inicio a=new Inicio(Propiedades,this.Principal);
        this.setVisible(false);
        try {
            this.finalize();
        }catch(Throwable ex){}
        this.Principal.setSize(890,575);
        this.Principal.setContentPane(a);
    }//GEN-LAST:event_RegresarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Salir();
    }//GEN-LAST:event_SalirActionPerformed

    private void EliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPersonaActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_EliminarPersonaActionPerformed

    private void ModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPersonaActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_ModificarPersonaActionPerformed

    private void CargarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarPersonaActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_CargarPersonaActionPerformed

    private void MostrarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPersonasActionPerformed
       Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_MostrarPersonasActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
       Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_MostrarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(Propiedades.isEmpty()){
            Ventana_Mensaje("No hay Personas cargadas","/imagenes/Emoji1.png");
        }
        else{
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
         /*BuscarPorDNI b2=new BuscarPorDNI(Propiedades,this.Principal,this);
        this.setVisible(false);
        try {
            this.finalize();
        }catch (Throwable ex){}
        this.Principal.setSize(455,320);
        this.Principal.setContentPane(b2);*/}
    }//GEN-LAST:event_BuscarActionPerformed

    private void Mostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar2ActionPerformed
        Ventana_Mensaje("Proximamente!!","/imagenes/Emoji1.png");
    }//GEN-LAST:event_Mostrar2ActionPerformed
 public void Salir(){
     try{
         Propiedades.GuardarEnArchivoTxt();}
     catch(IOException e){
         JOptionPane.showMessageDialog(null,"Error guardando los archivos \n"+e.toString(),"Error",JOptionPane.ERROR_MESSAGE);}
        System.exit(1);
}  
public void Ventana_Mensaje(String Imprimir, String imagen) {
    Icon icono = new javax.swing.ImageIcon(getClass().getResource(imagen));
    JLabel texto = new javax.swing.JLabel();
    texto.setFont(new java.awt.Font("Microsoft YaHei", 1, 16));
    texto.setText(Imprimir);
    JOptionPane.showMessageDialog(this, texto, "Lo sentimos!", JOptionPane.PLAIN_MESSAGE, icono); 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arriba;
    private javax.swing.JLabel Baja;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton CargarPersona;
    private javax.swing.JLabel CargarPersonaIm;
    private javax.swing.JButton EliminarPersona;
    private javax.swing.JLabel LogoFacu;
    private javax.swing.JLabel Modi;
    private javax.swing.JButton ModificarPersona;
    private javax.swing.JButton Mostrar;
    private javax.swing.JLabel Mostrar1;
    private javax.swing.JButton Mostrar2;
    private javax.swing.JLabel MostrarB;
    private javax.swing.JButton MostrarPersonas;
    private javax.swing.JPanel PanelAdmPersonas;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
